name: Basic Test of Go

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        platform: [ ubuntu-20.04, macos-latest, windows-latest ]
        go-version: [ 1.14.x, 1.16.x ]
    runs-on: ${{ matrix.platform }}
    name: Unit Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run Go test
        run: go test -v -cover ./...