name: Basic Test of Go

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
        go-version: [ 1.14.x ]
        timezone-unix: [ UTC, Asia/Taiwan, America/New_York ]
        timezone-windows: [ GMT, Taipei Standard Time, US Eastern Standard Time ]
    runs-on: ${{ matrix.platform }}
    name: Unit Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Change Timezone Unix
        uses: szenius/set-timezone@v1.0
        with: 
          timezoneLinux: ${{ matrix.timezone-unix }}
        if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}

      - name: Change Timezone Windows
        uses: szenius/set-timezone@v1.0
        with: 
          timezoneWindows: ${{ matrix.timezone-windows }}
        if: ${{ runner.os == 'Windows' }}

      - name: Run Go test
        run: go test -v -cover ./...