name: Basic Test of Go

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-ubunutu:
    strategy:
      matrix:
        go-version: [ 1.16.x ]
        timezone-unix: [ UTC, Asia/Taiwan, America/New_York ]
    runs-on: ubuntu-latest
    name: Unit Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Change Timezone Unix
        uses: szenius/set-timezone@v1.0
        with: 
          timezoneLinux: ${{ matrix.timezone-unix }}

      - name: Run Go test
        run: go test -v -cover ./...

  test-macos:
    strategy:
      matrix:
        go-version: [ 1.16.x ]
        timezone-unix: [ UTC, Asia/Taiwan, America/New_York ]
    runs-on: macos-latest
    name: Unit Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Change Timezone Unix
        uses: szenius/set-timezone@v1.0
        with: 
          timezoneMacos: ${{ matrix.timezone-unix }}

      - name: Run Go test
        run: go test -v -cover ./...

  test-windows:
    strategy:
      matrix:
        go-version: [ 1.16.x ]
        timezone-windows: [ GMT, Taipei Standard Time, US Eastern Standard Time ]
    runs-on: windows-latest
    name: Unit Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Change Timezone Windows
        uses: szenius/set-timezone@v1.0
        with: 
          timezoneWindows: ${{ matrix.timezone-windows }}

      - name: Run Go test
        run: go test -v -cover ./...